spring.application.name=backend
server.servlet.context-path=/api
spring.datasource.url=jdbc:postgresql://localhost:5432/database
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.security=DEBUG
api.security.token.secret=secret-1234
